apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cbl-maikosh-app
  labels:
    application: cbl-maikosh
    environment: prod
    tier: web
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
    autoscaling.knative.dev/minScale: "1"
    autoscaling.knative.dev/maxScale: "100"
    run.googleapis.com/cpu-throttling: "true"
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        application: cbl-maikosh
        environment: prod
        tier: web
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/zeidgeistdotcom/locations/us-central1/connectors/cbl-maikosh-connector
        run.googleapis.com/vpc-access-egress: all-traffic
        run.googleapis.com/secrets: |
          auth0-secret:latest,
          auth0-client-id:latest,
          auth0-client-secret:latest,
          auth0-issuer-url:latest,
          firebase-api-key:latest,
          firebase-auth-domain:latest,
          firebase-project-id:latest,
          firebase-storage-bucket:latest,
          firebase-messaging-sender-id:latest,
          firebase-app-id:latest,
          ga-measurement-id:latest
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      serviceAccountName: cbl-maikosh-service@zeidgeistdotcom.iam.gserviceaccount.com
      containers:
      - image: us-central1-docker.pkg.dev/zeidgeistdotcom/cbl-maikosh-repo/cbl-maikosh-app:latest
        name: cbl-maikosh-app
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Application Environment Variables
        - name: NODE_ENV
          value: "production"
        - name: GCP_PROJECT_ID
          value: "zeidgeistdotcom"
        - name: GCP_STORAGE_BUCKET
          value: "cbl-maikosh-prod-storage-zeidgeistdotcom"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: HOSTNAME
          value: "0.0.0.0"
        - name: PORT
          value: "8080"
        # Public API URLs (dynamically set during deployment)
        - name: NEXT_PUBLIC_API_URL
          value: "https://cbl-maikosh-app-prod-zeidgeistdotcom.a.run.app/api"
        - name: AUTH0_BASE_URL
          value: "https://cbl-maikosh-app-prod-zeidgeistdotcom.a.run.app"
        
        # Secret Environment Variables (from Google Secret Manager)
        - name: AUTH0_SECRET
          valueFrom:
            secretKeyRef:
              key: auth0-secret
              name: auth0-secret
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: auth0-client-id
              name: auth0-client-id
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: auth0-client-secret
              name: auth0-client-secret
        - name: AUTH0_ISSUER_BASE_URL
          valueFrom:
            secretKeyRef:
              key: auth0-issuer-url
              name: auth0-issuer-url
        - name: FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              key: firebase-api-key
              name: firebase-api-key
        - name: FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              key: firebase-auth-domain
              name: firebase-auth-domain
        - name: FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              key: firebase-project-id
              name: firebase-project-id
        - name: FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              key: firebase-storage-bucket
              name: firebase-storage-bucket
        - name: FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              key: firebase-messaging-sender-id
              name: firebase-messaging-sender-id
        - name: FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              key: firebase-app-id
              name: firebase-app-id
        - name: GA_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              key: ga-measurement-id
              name: ga-measurement-id
        
        # Resource allocation
        resources:
          limits:
            cpu: "2000m"
            memory: "2Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1
        
        # Security context
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
  traffic:
  - percent: 100
    latestRevision: true