steps:
  # Build the container image with optimization
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app:$BUILD_ID'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app:latest'
      - '--cache-from'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app:latest'
      - '--build-arg'
      - 'BUILDKIT_INLINE_CACHE=1'
      - '.'
  
  # Push both tagged images to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app']
  
  # Deploy container image to Cloud Run with comprehensive settings
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cbl-alloui-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '900'
      - '--concurrency'
      - '1000'
      - '--max-instances'
      - '100'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--service-account'
      - 'cbl-alloui-service@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - '^#^NODE_ENV=production#NEXT_PUBLIC_API_URL=https://cbl-alloui-app-$_ENVIRONMENT-$PROJECT_ID.a.run.app/api#AUTH0_BASE_URL=https://cbl-alloui-app-$_ENVIRONMENT-$PROJECT_ID.a.run.app#GCP_PROJECT_ID=$PROJECT_ID#FIREBASE_PROJECT_ID=$PROJECT_ID#GCP_STORAGE_BUCKET=cbl-alloui-$_ENVIRONMENT-storage-$PROJECT_ID#NEXT_TELEMETRY_DISABLED=1'
      - '--set-secrets'
      - '^#^AUTH0_SECRET=auth0-secret:latest#AUTH0_CLIENT_ID=auth0-client-id:latest#AUTH0_CLIENT_SECRET=auth0-client-secret:latest#AUTH0_ISSUER_BASE_URL=auth0-issuer-url:latest#NEXT_PUBLIC_FIREBASE_API_KEY=next-public-firebase-api-key:latest#NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=next-public-firebase-auth-domain:latest#NEXT_PUBLIC_FIREBASE_PROJECT_ID=next-public-firebase-project-id:latest#NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=next-public-firebase-storage-bucket:latest#NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=next-public-firebase-messaging-sender-id:latest#NEXT_PUBLIC_FIREBASE_APP_ID=next-public-firebase-app-id:latest#NEXT_PUBLIC_GA_MEASUREMENT_ID=next-public-ga-measurement-id:latest'
      - '--labels'
      - 'environment=$_ENVIRONMENT,application=cbl-alloui,tier=web'
      - '--tag'
      - '$_ENVIRONMENT'
  
  # Configure traffic allocation (100% to latest revision)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - 'cbl-alloui-app'
      - '--to-latest'
      - '--region'
      - 'us-central1'

# Substitutions for environment-specific deployments
substitutions:
  _ENVIRONMENT: 'prod'

# Images to be pushed to registry
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app:$BUILD_ID'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cbl-alloui-repo/cbl-alloui-app:latest'

# Build configuration
timeout: '2400s'  # 40 minutes
options:
  machineType: 'E2_HIGHCPU_8'  # High CPU for faster builds
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY